---
- name: System details
  debug: msg="{{ item }}"
  with_items:
  - "{{ ansible_distribution }}"
  - "{{ ansible_distribution_version }}"
  - "{{ ansible_distribution_major_version }}"

- name: ping
  ansible.builtin.ping:

- name: vars
  debug: msg="{{ item.state }}"
  when: item.state == "present"
  with_items:
    - "{{ lxc }}"

- name: hostvars
  debug: msg="{{ hostvars['qbittorrent'].ansible_host }}"

#- name: echo
##  debug: msg="{{ lxc[lookup('Media')]['vmid'] }}"
#  debug: msg="{{ lxc[hostname] }}"
#  ansible.builtin.shell: echo "{{ lxc.vmid['Media'] }}"

