---
- name: System details
  debug: msg="{{ item }}"
  with_items:
  - "{{ ansible_distribution }}"
  - "{{ ansible_distribution_version }}"
  - "{{ ansible_distribution_major_version }}"

- name: ping
  ansible.builtin.ping:

- name: vars
  debug: msg="{{ item.state }}"
  when: item.state == "present"
  with_items:
    - "{{ services }}"
