proxmox:
  hosts:
    reed:
      ansible_connection: ssh
      ansible_user: root
      ansible_host: 192.168.1.100

lxc:
  hosts:
    DNS:
      ansible_connection: ssh
      ansible_user: root
      ansible_host: 192.168.1.151
    VPN:
      ansible_connection: ssh
      ansible_user: root
      ansible_host: 192.168.1.152
    Media:
      ansible_connection: ssh
      ansible_user: root
      ansible_host: 192.168.1.153
